
  /*******************************************************************
  * ShoppingCartService.java
  * Generated by Backendless Corp.
  ********************************************************************/
		
package sharehome.com.androidsharehome2.com.mbaas.service;

import com.backendless.Backendless;
import com.backendless.async.callback.AsyncCallback;
import java.util.*;

import sharehome.com.androidsharehome2.com.mbaas.service.ShoppingItem;

public class ShoppingCartService
{
    static final String BACKENDLESS_HOST = "https://api.backendless.com";
    static final String SERVICE_NAME = "ShoppingCartService";
    static final String SERVICE_VERSION_NAME = "1.0.0";
    static final String APP_VERSION = "v1";
    static final String APP_ID = "19E73C32-D357-313A-FF64-12612084E000";
    static final String SECRET_KEY = "19F8B6BD-34A1-655C-FF3E-9BD31F1B0C00";

    private static ShoppingCartService ourInstance = new ShoppingCartService();

    private ShoppingCartService(  )
    {
    }

    public static ShoppingCartService getInstance()
    {
        return ourInstance;
    }

    public static void initApplication()
    {
        Backendless.setUrl( ShoppingCartService.BACKENDLESS_HOST );
        // if you invoke this sample inside of android application, you should use overloaded "initApp" with "context" argument
        Backendless.initApp(  ShoppingCartService.APP_ID, ShoppingCartService.SECRET_KEY, ShoppingCartService.APP_VERSION );
    }


    
    public boolean deleteItem(java.lang.String cartName, java.lang.String productName)
    {
        Object[] args = new Object[]{cartName, productName};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "deleteItem", args, boolean.class );
    }
    
    public void deleteItemAsync(java.lang.String cartName, java.lang.String productName, AsyncCallback<Boolean> callback)
    {
        Object[] args = new Object[]{cartName, productName};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "deleteItem", args, Boolean.class, callback);
    }
    
    public java.util.List<sharehome.com.androidsharehome2.com.mbaas.service.ShoppingItem> getItems(java.lang.String cartName)
    {
        Object[] args = new Object[]{cartName};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getItems", args, java.util.List.class );
    }
    
    public void getItemsAsync(java.lang.String cartName, AsyncCallback<java.util.List<sharehome.com.androidsharehome2.com.mbaas.service.ShoppingItem>> callback)
    {
        Object[] args = new Object[]{cartName};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getItems", args, java.util.List.class, callback);
    }
    
    public void addItem(java.lang.String cartName, sharehome.com.androidsharehome2.com.mbaas.service.ShoppingItem item)
    {
        Object[] args = new Object[]{cartName, item};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "addItem", args );
    }
    
    public void addItemAsync(java.lang.String cartName, sharehome.com.androidsharehome2.com.mbaas.service.ShoppingItem item, AsyncCallback<Object> callback)
    {
        Object[] args = new Object[]{cartName, item};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "addItem", args, Object.class, callback);
    }
    
}
