
  /*******************************************************************
  * Grocery.java
  * Generated by Backendless Corp.
  ********************************************************************/
		package sharehome.com.androidsharehome2.backend;

public class Grocery
{
    private java.lang.String groceryName;
    private java.lang.String groupId;
    private java.lang.String objectId;
    private java.lang.String ownerId;
    private int status;
    public void setGroceryName(java.lang.String groceryName)
    {
      this.groceryName = groceryName;
    }
    public void setGroupId(java.lang.String groupId)
    {
      this.groupId = groupId;
    }
    public void setObjectId(java.lang.String objectId)
    {
      this.objectId = objectId;
    }
    public void setOwnerId(java.lang.String ownerId)
    {
      this.ownerId = ownerId;
    }
    public void setStatus(int status)
    {
      this.status = status;
    }
    public java.lang.String getGroceryName( )
    {
      return groceryName;
    }
    public java.lang.String getGroupId( )
    {
      return groupId;
    }
    public java.lang.String getObjectId( )
    {
      return objectId;
    }
    public java.lang.String getOwnerId( )
    {
      return ownerId;
    }
    public int getStatus( )
    {
      return status;
    }
}