
  /*******************************************************************
  * Post.java
  * Generated by Backendless Corp.
  ********************************************************************/
		package sharehome.com.androidsharehome2.backend;

public class Post
{
    private boolean anonymous;
    private java.lang.String content;
    private int downVote;
    private java.lang.String groupId;
    private java.lang.String objectId;
    private java.lang.String ownerId;
    private java.lang.String postTitle;
    private int upVote;
    private java.lang.String userId;
    private java.lang.String votedList;
    public void setAnonymous(boolean anonymous)
    {
      this.anonymous = anonymous;
    }
    public void setContent(java.lang.String content)
    {
      this.content = content;
    }
    public void setDownVote(int downVote)
    {
      this.downVote = downVote;
    }
    public void setGroupId(java.lang.String groupId)
    {
      this.groupId = groupId;
    }
    public void setObjectId(java.lang.String objectId)
    {
      this.objectId = objectId;
    }
    public void setOwnerId(java.lang.String ownerId)
    {
      this.ownerId = ownerId;
    }
    public void setPostTitle(java.lang.String postTitle)
    {
      this.postTitle = postTitle;
    }
    public void setUpVote(int upVote)
    {
      this.upVote = upVote;
    }
    public void setUserId(java.lang.String userId)
    {
      this.userId = userId;
    }
    public void setVotedList(java.lang.String votedList)
    {
      this.votedList = votedList;
    }
    public boolean getAnonymous( )
    {
      return anonymous;
    }
    public java.lang.String getContent( )
    {
      return content;
    }
    public int getDownVote( )
    {
      return downVote;
    }
    public java.lang.String getGroupId( )
    {
      return groupId;
    }
    public java.lang.String getObjectId( )
    {
      return objectId;
    }
    public java.lang.String getOwnerId( )
    {
      return ownerId;
    }
    public java.lang.String getPostTitle( )
    {
      return postTitle;
    }
    public int getUpVote( )
    {
      return upVote;
    }
    public java.lang.String getUserId( )
    {
      return userId;
    }
    public java.lang.String getVotedList( )
    {
      return votedList;
    }
}