
  /*******************************************************************
  * Transaction.java
  * Generated by Backendless Corp.
  ********************************************************************/
		package sharehome.com.androidsharehome2.backend;

public class Transaction
{
    private java.lang.String content;
    private java.lang.String groupId;
    private java.lang.String objectId;
    private java.lang.String otherPeople;
    private java.lang.String ownerId;
    private java.lang.String requestor;
    private double transAmount;
    private java.lang.String transTitle;
    public void setContent(java.lang.String content)
    {
      this.content = content;
    }
    public void setGroupId(java.lang.String groupId)
    {
      this.groupId = groupId;
    }
    public void setObjectId(java.lang.String objectId)
    {
      this.objectId = objectId;
    }
    public void setOtherPeople(java.lang.String otherPeople)
    {
      this.otherPeople = otherPeople;
    }
    public void setOwnerId(java.lang.String ownerId)
    {
      this.ownerId = ownerId;
    }
    public void setRequestor(java.lang.String requestor)
    {
      this.requestor = requestor;
    }
    public void setTransAmount(double transAmount)
    {
      this.transAmount = transAmount;
    }
    public void setTransTitle(java.lang.String transTitle)
    {
      this.transTitle = transTitle;
    }
    public java.lang.String getContent( )
    {
      return content;
    }
    public java.lang.String getGroupId( )
    {
      return groupId;
    }
    public java.lang.String getObjectId( )
    {
      return objectId;
    }
    public java.lang.String getOtherPeople( )
    {
      return otherPeople;
    }
    public java.lang.String getOwnerId( )
    {
      return ownerId;
    }
    public java.lang.String getRequestor( )
    {
      return requestor;
    }
    public double getTransAmount( )
    {
      return transAmount;
    }
    public java.lang.String getTransTitle( )
    {
      return transTitle;
    }
}