
  /*******************************************************************
  * GroceryService.java
  * Generated by Backendless Corp.
  ********************************************************************/
		
package sharehome.com.androidsharehome2.backend;

import com.backendless.Backendless;
import com.backendless.async.callback.AsyncCallback;
import java.util.*;

import sharehome.com.androidsharehome2.backend.Grocery;

public class GroceryService
{
    static final String BACKENDLESS_HOST = "https://api.backendless.com";
    static final String SERVICE_NAME = "GroceryService";
    static final String SERVICE_VERSION_NAME = "1.0.0";
    static final String APP_VERSION = "v1";
    static final String APP_ID = "19E73C32-D357-313A-FF64-12612084E000";
    static final String SECRET_KEY = "19F8B6BD-34A1-655C-FF3E-9BD31F1B0C00";

    private static GroceryService ourInstance = new GroceryService();

    private GroceryService(  )
    {
    }

    public static GroceryService getInstance()
    {
        return ourInstance;
    }

    public static void initApplication()
    {
        Backendless.setUrl( GroceryService.BACKENDLESS_HOST );
        // if you invoke this sample inside of android application, you should use overloaded "initApp" with "context" argument
        Backendless.initApp( GroceryService.APP_ID, GroceryService.SECRET_KEY, GroceryService.APP_VERSION );
    }


    
    public java.lang.String createNewGrocery(java.lang.String groupId, java.lang.String groceryName, int status)
    {
        Object[] args = new Object[]{groupId, groceryName, status};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "createNewGrocery", args, java.lang.String.class );
    }
    
    public void createNewGroceryAsync(java.lang.String groupId, java.lang.String groceryName, int status, AsyncCallback<java.lang.String> callback)
    {
        Object[] args = new Object[]{groupId, groceryName, status};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "createNewGrocery", args, java.lang.String.class, callback);
    }
    
    public sharehome.com.androidsharehome2.backend.Grocery getGroceryById(java.lang.String groceryId)
    {
        Object[] args = new Object[]{groceryId};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getGroceryById", args, sharehome.com.androidsharehome2.backend.Grocery.class );
    }
    
    public void getGroceryByIdAsync(java.lang.String groceryId, AsyncCallback<sharehome.com.androidsharehome2.backend.Grocery> callback)
    {
        Object[] args = new Object[]{groceryId};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getGroceryById", args, sharehome.com.androidsharehome2.backend.Grocery.class, callback);
    }
    
    public boolean deleteGrocery(java.lang.String groceryId, java.lang.String groupId)
    {
        Object[] args = new Object[]{groceryId, groupId};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "deleteGrocery", args, boolean.class );
    }
    
    public void deleteGroceryAsync(java.lang.String groceryId, java.lang.String groupId, AsyncCallback<Boolean> callback)
    {
        Object[] args = new Object[]{groceryId, groupId};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "deleteGrocery", args, Boolean.class, callback);
    }
    
    public int changeStatus(java.lang.String groceryId)
    {
        Object[] args = new Object[]{groceryId};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "changeStatus", args, int.class );
    }
    
    public void changeStatusAsync(java.lang.String groceryId, AsyncCallback<Integer> callback)
    {
        Object[] args = new Object[]{groceryId};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "changeStatus", args, Integer.class, callback);
    }
    
}
