
  /*******************************************************************
  * Group.java
  * Generated by Backendless Corp.
  ********************************************************************/
		package sharehome.com.androidsharehome2.backend;

public class Group
{
    private java.lang.String groceryIdList;
    private java.lang.String groupName;
    private java.lang.String leaderId;
    private java.lang.String objectId;
    private java.lang.String ownerId;
    private java.lang.String postIdList;
    private java.lang.String taskIdList;
    private java.lang.String teamMembersList;
    private java.lang.String transactionIdList;
    public void setGroceryIdList(java.lang.String groceryIdList)
    {
      this.groceryIdList = groceryIdList;
    }
    public void setGroupName(java.lang.String groupName)
    {
      this.groupName = groupName;
    }
    public void setLeaderId(java.lang.String leaderId)
    {
      this.leaderId = leaderId;
    }
    public void setObjectId(java.lang.String objectId)
    {
      this.objectId = objectId;
    }
    public void setOwnerId(java.lang.String ownerId)
    {
      this.ownerId = ownerId;
    }
    public void setPostIdList(java.lang.String postIdList)
    {
      this.postIdList = postIdList;
    }
    public void setTaskIdList(java.lang.String taskIdList)
    {
      this.taskIdList = taskIdList;
    }
    public void setTeamMembersList(java.lang.String teamMembersList)
    {
      this.teamMembersList = teamMembersList;
    }
    public void setTransactionIdList(java.lang.String transactionIdList)
    {
      this.transactionIdList = transactionIdList;
    }
    public java.lang.String getGroceryIdList( )
    {
      return groceryIdList;
    }
    public java.lang.String getGroupName( )
    {
      return groupName;
    }
    public java.lang.String getLeaderId( )
    {
      return leaderId;
    }
    public java.lang.String getObjectId( )
    {
      return objectId;
    }
    public java.lang.String getOwnerId( )
    {
      return ownerId;
    }
    public java.lang.String getPostIdList( )
    {
      return postIdList;
    }
    public java.lang.String getTaskIdList( )
    {
      return taskIdList;
    }
    public java.lang.String getTeamMembersList( )
    {
      return teamMembersList;
    }
    public java.lang.String getTransactionIdList( )
    {
      return transactionIdList;
    }
}