
  /*******************************************************************
  * Task.java
  * Generated by Backendless Corp.
  ********************************************************************/
		package sharehome.com.androidsharehome2.backend;

public class Task
{
    private int duration;
    private java.lang.String groupId;
    private java.lang.String membersIdList;
    private java.lang.String objectId;
    private java.lang.String ownerId;
    private java.util.Date startTime;
    private java.lang.String taskName;
    private java.lang.String userOnDuty;
    public void setDuration(int duration)
    {
      this.duration = duration;
    }
    public void setGroupId(java.lang.String groupId)
    {
      this.groupId = groupId;
    }
    public void setMembersIdList(java.lang.String membersIdList)
    {
      this.membersIdList = membersIdList;
    }
    public void setObjectId(java.lang.String objectId)
    {
      this.objectId = objectId;
    }
    public void setOwnerId(java.lang.String ownerId)
    {
      this.ownerId = ownerId;
    }
    public void setStartTime(java.util.Date startTime)
    {
      this.startTime = startTime;
    }
    public void setTaskName(java.lang.String taskName)
    {
      this.taskName = taskName;
    }
    public void setUserOnDuty(java.lang.String userOnDuty)
    {
      this.userOnDuty = userOnDuty;
    }
    public int getDuration( )
    {
      return duration;
    }
    public java.lang.String getGroupId( )
    {
      return groupId;
    }
    public java.lang.String getMembersIdList( )
    {
      return membersIdList;
    }
    public java.lang.String getObjectId( )
    {
      return objectId;
    }
    public java.lang.String getOwnerId( )
    {
      return ownerId;
    }
    public java.util.Date getStartTime( )
    {
      return startTime;
    }
    public java.lang.String getTaskName( )
    {
      return taskName;
    }
    public java.lang.String getUserOnDuty( )
    {
      return userOnDuty;
    }
}